import { Subscription } from '@/types/subscription'

export const DEMO_SUBSCRIPTIONS: Subscription[] = [
  {
    id: 'demo-1',
    user_id: 'demo',
    name: 'GitHub',
    description: 'Source code hosting, CI/CD and collaboration',
    url: 'https://github.com',
    price: 9.99,
    currency: 'EUR',
    billing_cycle: 'monthly',
    start_date: '2025-01-15',
    renewal_date: '2026-04-15',
    status: 'active',
    usage_status: 'high',
    category: 'development',
    notes: null,
    api_key_linked: false,
    created_at: '2025-01-15T00:00:00Z',
    updated_at: '2025-01-15T00:00:00Z',
  },
  {
    id: 'demo-2',
    user_id: 'demo',
    name: 'Figma',
    description: 'UI/UX design and prototyping tool',
    url: 'https://figma.com',
    price: 144,
    currency: 'EUR',
    billing_cycle: 'yearly',
    start_date: '2025-08-01',
    renewal_date: '2026-08-01',
    status: 'active',
    usage_status: 'medium',
    category: 'design',
    notes: 'Professional plan, 3 editors',
    api_key_linked: false,
    created_at: '2025-08-01T00:00:00Z',
    updated_at: '2025-08-01T00:00:00Z',
  },
  {
    id: 'demo-3',
    user_id: 'demo',
    name: 'Slack',
    description: 'Team communication and messaging',
    url: 'https://slack.com',
    price: 7.25,
    currency: 'EUR',
    billing_cycle: 'monthly',
    start_date: '2025-03-01',
    renewal_date: '2026-04-01',
    status: 'active',
    usage_status: 'high',
    category: 'communication',
    notes: null,
    api_key_linked: false,
    created_at: '2025-03-01T00:00:00Z',
    updated_at: '2025-03-01T00:00:00Z',
  },
  {
    id: 'demo-4',
    user_id: 'demo',
    name: 'Adobe Creative Cloud',
    description: 'Photoshop, Illustrator, Premiere Pro...',
    url: 'https://adobe.com',
    price: 59.99,
    currency: 'EUR',
    billing_cycle: 'monthly',
    start_date: '2024-06-01',
    renewal_date: '2026-04-10',
    status: 'paused',
    usage_status: 'low',
    category: 'design',
    notes: 'Paused — review if still needed',
    api_key_linked: true,
    created_at: '2024-06-01T00:00:00Z',
    updated_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'demo-5',
    user_id: 'demo',
    name: 'AWS',
    description: 'Cloud infrastructure and hosting',
    url: 'https://aws.amazon.com',
    price: 89.50,
    currency: 'EUR',
    billing_cycle: 'monthly',
    start_date: '2024-01-01',
    renewal_date: '2026-04-01',
    status: 'active',
    usage_status: 'high',
    category: 'development',
    notes: 'EC2 + S3 + RDS bundle',
    api_key_linked: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'demo-6',
    user_id: 'demo',
    name: 'Notion',
    description: 'Notes, docs and project management',
    url: 'https://notion.so',
    price: 8,
    currency: 'EUR',
    billing_cycle: 'monthly',
    start_date: '2026-03-01',
    renewal_date: '2026-04-03',
    status: 'trial',
    usage_status: 'medium',
    category: 'productivity',
    notes: 'Free trial ends soon',
    api_key_linked: false,
    created_at: '2026-03-01T00:00:00Z',
    updated_at: '2026-03-01T00:00:00Z',
  },
]
